# This is a template for configuration file used by switch
# This is a test for the configuration file for the get_inputs
# For connecting to the database we need add the .env file where we place the environment
# variables for your own computer
---

# ------------------
# General config
# ------------------
version: 3.0
inputs_dir: inputs

# --------------------------------
# Config used by switch get_inputs
# --------------------------------
get_inputs:
  # Database information
  schema: switch

  # Scenario configuration
  scenario_id: 176
  #  the following parameters are optional and will override the defaults for that scenario
  #  this should only be used for preliminary exploration of scenarios or for testing
  #  if a scenario is part of research, it should be included in the database as a row in the scenarios table.
  #
  # -1 is equivalent to null
  #  study_timeframe_id:
  #  time_sample_id:
  #  demand_scenario_id:
  #  fuel_simple_price_scenario_id:
  #  generation_plant_scenario_id:
  #  generation_plant_cost_scenario_id:
  #  generation_plant_existing_and_planned_scenario_id:
  #  hydro_simple_scenario_id:
  #  carbon_cap_scenario_id:
  #  supply_curves_scenario_id:
  #  regional_fuel_market_scenario_id:
  #  rps_scenario_id:
  #  enable_dr:
  #  enable_ev:
  #  transmission_base_capital_cost_scenario_id:
  #  ca_policies_scenario_id:
  #  enable_planning_reserves:
  #  generation_plant_technologies_scenario_id:
  #  variable_o_m_cost_scenario_id:
  #  wind_to_solar_ratio:
post_process_steps: # The following post process steps will be run in order
#  - add_storage # Used by Martin when studying LDES, likely shouldn't uncomment this line
#  - aggregate_candidate_projects
  - replace_plants_in_zone_all
  - create_graph_files
#  - energy_cost
  - fix_prebuild_conflict
#  - derate_hydro
#  - only_california
#  - reserve_technologies
post_process_config:
#   add_storage was used by Martin when studying LDES you likely don't need to uncomment these parameters
#   add_storage:
#     costs_scenario: 0
#     plants_scenario: 0
#     constant_scenario: 0
#     minimums_scenario: 0

#   When the following lines are uncommented all the Central_PV and Wind projects within the same load zone gets
#   aggregated into a single project. This helps reduce the model complexity.
#   cf_quantile is the percentile for the capacity factor to use. 1 will use the largest capacity factor
#   of all the available candidate plants, 0.5 will use the median plant and 0 will use the worst plant.
#   aggregate_candidate_projects:
#     agg_techs: ["Central_PV"]
#     cf_method: "file" # Other options are "weighted_mean" and "95_quantile"
#   derate_hydro: 0.75 # Amount to de-rate the hydro by.
